[metadata]
name = json_prettifier
version = 1.4.9
author = "Isaac Onagh"
author_email = "adnanonagh@gmail.com"
url = https://github.com/"unforgivenii147"/json_prettifier

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.13

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    jb = json_prettifier.cli:main

